name: iOS Build & Detox

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 25
    defaults:
      run:
        working-directory: ./example

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Node
      uses: actions/setup-node@v2.1.5

    - name: Access Token
      run: echo $MAPBOX_ACCESS_TOKEN > ./accesstoken
      env:
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

    - name: Install Dependencies      
      run: yarn install

    - name: Update Pods
      run: |
        gem update cocoapods xcodeproj
        (cd ios && pod install)

    - run: brew tap wix/brew
    - run: brew install applesimutils
    - run: yarn detox build
    - run: yarn detox test --debug-synchronization 200
