name: iOS Build & Detox

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./example

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Node
      uses: actions/setup-node@v2.1.5

    - name: Cache node modules
      uses: actions/cache@v2
      id: cache
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Access Token
      run: echo $MAPBOX_ACCESS_TOKEN > ./accesstoken
      env:
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

    - name: Rebuild detox
      if: steps.cache.outputs.cache-hit == 'true'
      run: yarn detox clean-framework-cache && yarn detox build-framework-cache

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Cache Pods
      uses: actions/cache@v2
      id: podcache
      with:
        path: ios/Pods
        key: pods-${{ hashFiles('**/Podfile.lock') }}

    - name: Update Pods
      run: |
        gem update cocoapods xcodeproj
        (cd ios && pod install)

    - run: brew tap wix/brew
    - run: brew install applesimutils
    - run: yarn detox build --configuration ios
    - run: yarn detox test --configuration ios --cleanup
